### ISSUE TITLE
git::config define error

### ISSUE THREAD

**Issue by kostyrevaa** [nesi/puppet-git#40] opened 2015-02-03 14:42 UTC
```
include git
git::config { 'core.excludesfile':
    value    => "/opt/svn/tutu-tools/git/.gitignore",
    user     => 'root',
    provider => 'system',
}
```
produces error
```
Warning: Exec[git_config_core.excludesfile](provider=posix): Cannot understand environment setting "HOME="
```

**Comment by Aethylred** [comment] 2015-02-03 20:52
I think this is a duplicate of #40, provided the fix for it includes specifying the `HOME` environment variable correctly.

**Closed by Aethylred** 2015-02-03 20:52 UTC
